site_name: LXCSNotes
site_description: 计算机科学与技术学习笔记
site_author: Amonologue
copyright: Copyright &copy; 2025 LXCSNotes | 使用 <a href='https://squidfunk.github.io/mkdocs-material/' target='_blank'>Material for MkDocs</a>

repo_url: https://github.com/A-Egoist/LXCSNotes/tree/main
# site_url: https://your-domain.com  # 可选
repo_url: https://github.com/yourname/lxcsnotes  # 可选

# 主题配置
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - content.code.annotate
  palette:
    primary: indigo
    accent: blue

# 扩展配置 (关键部分)
markdown_extensions:
  - pymdownx.highlight:         # 代码高亮
      anchor_linenums: true
      line_spans: __span
      pygments_style: material
      use_pygments: true
  - pymdownx.inlinehilite       # 行内代码高亮
  - pymdownx.superfences        # 代码块嵌套
  - pymdownx.arithmatex:        # LaTeX 支持
      generic: true
  - pymdownx.tasklist:          # 任务列表 (Typora 兼容)
      custom_checkbox: true
  - pymdownx.emoji:             # 表情符号
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition                  # 彩色提示框
  - toc:                        # 目录
      permalink: true
  - attr_list                   # 属性列表
  - md_in_html                  # HTML 中嵌入 Markdown

# 数学公式渲染 (MathJax)
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 插件
plugins:
  - search
  - git-revision-date

# 导航
nav:
  - Home: index.md
  - Algorithms: algorithms.md
  - Systems: systems.md
  # 添加更多笔记...

# 自定义目录
docs_dir: 'docs'