site_name: LXCSNotes
site_description: 计算机科学与技术学习笔记
site_author: Amonologue
# site_favicon: favicon.ico
copyright: Copyright &copy; 2025 LXCSNotes | 使用 <a href='https://squidfunk.github.io/mkdocs-material/' target='_blank'>Material for MkDocs</a>

repo_url: https://github.com/A-Egoist/LXCSNotes/tree/main
# site_url: https://your-domain.com  # 可选

theme:
  name: material
  language: zh
  logo: assets/images/PenguinLogistics.png
  favicon: assets/images/favicon.png
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    scheme: default

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.arithmatex:  # 支持 LaTeX
      generic: true
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
  - pymdownx.tabbed
  - pymdownx.magiclink
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - attr_list  # 用于在 Markdown 中加 HTML 属性（如 class）

plugins:
  - search
  - glightbox
  - mermaid2

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js  # 支持 LaTeX 渲染
  - https://cdn.jsdelivr.net/npm/glightbox/dist/js/glightbox.min.js

extra_css:
  - https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css
  - stylesheets/extra.css